### ISSUE TITLE
Using empty TOPCONS prediction breaks SWAMP

### ISSUE THREAD

**Issue by FilomenoSanchez** [rigdenlab/SWAMP#25]
## System information

- Python version: 2.7
- Environment (if applicable): CCP4 7.1

## Problem description and context

Providing a TOPCONS prediction where no helices have been found breaks the pipeline

## Example

```bash
swamp-mr 5xef.mtz 5xef.fasta 5xef.psicov 5xef.topcons -max_concurrent_procs 70 -mtz_phases 5xef_phases.mtz -consco_threshold 0 -use_centroids -use_cores
```

## Traceback

```python
Traceback (most recent call last):
  File "/home/filo/opt/SWAMP/swamp/command_line/swamp-mr.py", line 210, in <module>
    main()
  File "/home/filo/opt/SWAMP/swamp/command_line/swamp-mr.py", line 114, in main
    queue_environment=args.environment, queue_name=args.queue)
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/py2/swamp/search/__init__.py", line 39, in SearchTarget
    return SearchTarget(*args, **kwargs)
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/py2/swamp/search/searchtarget.py", line 88, in __init__
    conformat=self.conformat, pdb_benchmark=self.target_pdb_benchmark)
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/py2/swamp/utils/__init__.py", line 49, in TargetSplit
    return TargetSplit(*args, **kwargs)
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/py2/swamp/utils/targetsplit.py", line 45, in __init__
    self.sspred.parse()
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/py2/swamp/parsers/topconsparser.py", line 58, in parse
    self._get_tmhelices_map()
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/py2/swamp/parsers/topconsparser.py", line 76, in _get_tmhelices_map
    self.tmhelices.columns = ["id", "start", "stop"]
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/python2.7/site-packages/pandas/core/generic.py", line 5080, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/python2.7/site-packages/pandas/core/generic.py", line 638, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/filo/opt/CCP4/ccp4-7.1/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 155, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
```

## Example input file:

[5xef_topcons.zip](https://github.com/rigdenlab/SWAMP/files/4638312/5xef_topcons.zip)

**Comment by FilomenoSanchez** [comment]
Closed by commit 6ffbfbed09b467afb3a52b5f091d1b6c859e077d
